export const cards = [
  {
    id: 1,
    coffeeType: ["TRADICIONAL", "ALCOÓLICO", "GELADO"],
    titleCard: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385103/coffees/Coffee-1_b22qbk.svg",
    price: 10,
  },
  {
    id: 2,
    coffeeType: ["TRADICIONAL", "COM LEITE"],
    titleCard: "sapo",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385103/coffees/Coffee-2_aetvr3.svg",
    price: 10,
  },
  {
    id: 3,
    coffeeType: ["TRADICIONAL", "ESPECIAL"],
    titleCard: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385103/coffees/Coffee-3_fvud10.svg",
    price: 10,
  },
  {
    id: 4,
    coffeeType: ["TRADICIONAL"],
    titleCard: "cachorro",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385103/coffees/Coffee-4_mpcxxc.svg",
  },
  {
    id: 5,
    coffeeType: ["TRADICIONAL", "ALCOÓLICO", "GELADO"],
    titleCard: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385104/coffees/Coffee-5_ctvmsl.svg",
    price: 10,
  },
  {
    id: 6,
    coffeeType: ["TRADICIONAL"],
    titleCard: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385104/coffees/Coffee-6_exclwv.svg",
    price: 10,
  },
  {
    id: 7,
    coffeeType: ["TRADICIONAL"],
    titleCard: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385105/coffees/Coffee-7_t19ky5.svg",
    price: 10,
  },
  {
    id: 8,
    coffeeType: ["TRADICIONAL"],
    titleCard: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385105/coffees/Coffee-8_ejbbyk.svg",
    price: 10,
  },
  {
    id: 9,
    coffeeType: ["TRADICIONAL"],
    titleCard: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385105/coffees/Coffee-9_nm1soh.svg",
    price: 10,
  },
  {
    id: 10,
    coffeeType: ["TRADICIONAL"],
    titleCard: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385105/coffees/Coffee-10_ntf8vz.svg",
    price: 10,
  },
  {
    id: 11,
    coffeeType: ["TRADICIONAL"],
    titleCard: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385105/coffees/Coffee-11_rtn41n.svg",
    price: 10,
  },
  {
    id: 12,
    coffeeType: ["TRADICIONAL"],
    titleCard: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385106/coffees/Coffee-12_zauyww.svg",
    price: 10,
  },
  {
    id: 13,
    coffeeType: ["TRADICIONAL"],
    titleCard: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385106/coffees/Coffee-12_zauyww.svg",
    price: 10,
  },
  {
    id: 14,
    coffeeType: ["TRADICIONAL"],
    titleCard: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    img: "https://res.cloudinary.com/dotpcgqlv/image/upload/v1675385106/coffees/Coffee-12_zauyww.svg",
    price: 10,
  },

];
